BooksApp/BooksApp.MVC/Areas/Admin/Models/BookListViewModel.cs
namespace BooksApp.MVC.Areas.Admin.Models
{
    public class BookListViewModel
    {
        public List<BookViewModel> BookViewModelList { get; set; }
        public string SourceAction { get; set; }
    }
}

BooksApp/BooksApp.MVC/Models/BookDetailsViewModel.cs
using System;
namespace BooksApp.MVC.Models
{
	public class BookDetailsViewModel
	{
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string ImageUrl { get; set; }
        public decimal Price { get; set; }
        public string AuthorName { get; set; }
        public string AuthorAbout { get; set; }
        public string AuthorUrl { get; set; }
        public string PublisherName { get; set; }
        public string PublisherUrl { get; set; }
        public List<CategoryViewModel> Categories { get; set; }
        public int EditionYear { get; set; }
        public int EditionNumber { get; set; }
        public int Stock { get; set; }
        public int PageCount { get; set; }
        public string Description { get; set; }
    }
}

BooksApp/BooksApp.MVC/Controllers/BooksShopController.cs
using BooksApp.Business.Abstract;
using BooksApp.Entity.Concrete;
using BooksApp.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace BooksApp.MVC.Controllers
{
    public class BooksShopController : Controller
    {
        private readonly IBookService _bookManager;

        public BooksShopController(IBookService bookManager)
        {
            _bookManager = bookManager;
        }

        public async Task<IActionResult> BookList(string categoryurl=null, string authorurl=null, string publisherurl=null)
        {
            List<Book> bookList = await _bookManager.GetAllActiveBooksAsync(categoryurl, authorurl, publisherurl);
            List<BookViewModel> bookViewModelList = bookList.Select(b => new BookViewModel
            {
                Id = b.Id,
                Name = b.Name,
                Price = b.Price,
                Url = b.Url,
                ImageUrl = b.ImageUrl,
                AuthorName = b.Author.FirstName + " " + b.Author.LastName,
                AuthorUrl = b.Author.Url,
                PublisherName = b.Publisher.Name,
                PublisherUrl = b.Publisher.Url
            }).ToList();
            return View(bookViewModelList);
        }
        public async Task<IActionResult> BookDetails(string url)
        {
            Book book = await _bookManager.GetBookByUrlAsync(url);
            BookDetailsViewModel bookDetailsViewModel = new BookDetailsViewModel
            {
                Id = book.Id,
                Name = book.Name,
                AuthorName = book.Author.FirstName + " " + book.Author.LastName,
                AuthorAbout = book.Author.About,
                AuthorUrl = book.Author.Url,
                Stock = book.Stock,
                Url = book.Url,
                ImageUrl = book.ImageUrl,
                Description = book.Description,
                EditionYear = book.EditionYear,
                EditionNumber = book.EditionNumber,
                PageCount = book.PageCount,
                Price = book.Price,
                PublisherName = book.Publisher.Name,
                PublisherUrl = book.Publisher.Url,
                Categories = book.BookCategories.Select(bc => new CategoryViewModel
                {
                    Name = bc.Category.Name,
                    Url = bc.Category.Url
                }).ToList()
            };
            return View(bookDetailsViewModel);
        }
    }
    
}

BooksApp/BooksApp.MVC/Controllers/CartController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using BooksApp.Business.Abstract;
using BooksApp.Entity.Concrete;
using BooksApp.Entity.Concrete.ComplexTypes;
using BooksApp.MVC.Models;
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BooksApp.MVC.Controllers
{
    [Authorize(Roles = "Admin, User")]
    public class CartController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ICartService _cartManager;
        private readonly ICartItemService _cartItemManager;
        private readonly IOrderService _orderManager;
        private readonly INotyfService _notyf;

        public CartController(UserManager<User> userManager, ICartService cartManager, INotyfService notyf, ICartItemService cartItemManager, IOrderService orderManager)
        {
            _userManager = userManager;
            _cartManager = cartManager;
            _notyf = notyf;
            _cartItemManager = cartItemManager;
            _orderManager = orderManager;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var cart = await _cartManager.GetCartByUserId(userId);
            CartViewModel model = new CartViewModel
            {
                CartId = cart.Id,
                CartItems = cart.CartItems
                    .Select(ci => new CartItemViewModel
                    {
                        CartItemId = ci.Id,
                        BookId = ci.Book.Id,
                        BookName = ci.Book.Name,
                        BookUrl = ci.Book.Url,
                        BookImageUrl = ci.Book.ImageUrl,
                        Price = ci.Book.Price,
                        Quantity = ci.Quantity
                    }).ToList()
            };
            return View(model);
        }
        public async Task<IActionResult> AddToCart(int id, int quantity)
        {
            var userId = _userManager.GetUserId(User);
            await _cartManager.AddToCart(userId, id, quantity);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> ChangeQuantity(int cartItemId, int quantity)
        {
            if (ModelState.IsValid)
            {
                await _cartItemManager.ChangeQuantityAsync(cartItemId, quantity);
            }
            else
            {
                _notyf.Warning("Lütfen adedi boş bırakmayınız");
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteItemFromCart(int id)
        {
            var cartItem = await _cartItemManager.GetByIdAsync(id);
            _cartItemManager.Delete(cartItem);
            _notyf.Success("Kitap sepetinizden silindi");
            return RedirectToAction("Index");
        }
        public IActionResult ClearCart(int id)
        {
            _cartItemManager.ClearCart(id);
            _notyf.Success("Sepetiniz boşaltılmıştır.");
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Checkout()
        {
            string userId = _userManager.GetUserId(User);
            User user = await _userManager.FindByIdAsync(userId);
            Cart cart = await _cartManager.GetCartByUserId(userId);
            OrderViewModel model = new OrderViewModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Address = user.Address,
                City = user.City,
                PhoneNumber = user.PhoneNumber,
                Email = user.Email,
                Cart = new CartViewModel
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(ci => new CartItemViewModel
                    {
                        CartItemId = ci.Id,
                        BookId = ci.BookId,
                        BookName = ci.Book.Name,
                        Price = ci.Book.Price,
                        Quantity = ci.Quantity,
                        BookImageUrl = ci.Book.ImageUrl
                    }).ToList()
                },
                CardName = "Alex de Souza",
                CardNumber = "5890040000000016",
                ExpirationYear = "2028",
                ExpirationMonth = "10",
                Cvc = "123"
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Checkout(OrderViewModel model)
        {
            string userId = _userManager.GetUserId(User);
            Cart cart = await _cartManager.GetCartByUserId(userId);
            if (ModelState.IsValid)
            {
                model.Cart = new CartViewModel
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(ci => new CartItemViewModel
                    {
                        CartItemId = ci.Id,
                        BookId = ci.BookId,
                        BookName = ci.Book.Name,
                        Price = ci.Book.Price,
                        BookImageUrl = ci.Book.ImageUrl,
                        Quantity = ci.Quantity
                    }).ToList()
                };
                Payment payment = PaymentProcess(model);
                if (payment.Status == "success")
                {
                    await SaveOrder(model, userId);
                    _cartItemManager.ClearCart(model.Cart.CartId);
                    _notyf.Success("Ödeme işlemi başarıyla tamamlanmıştır");
                    return RedirectToAction("Index", "Home");
                }
                _notyf.Error("Bir hata oluştu");
            }

            return View();
        }
        [NonAction]
        private Payment PaymentProcess(OrderViewModel model)
        {
            #region Options
            Options options = new Options();
            options.ApiKey = "sandbox-313Mg6w05g35vEZZXgG5dL5YW6LiUGJl";
            options.SecretKey = "sandbox-tkue5CZOz5usUARA3DmXPQAVnbJkcXx5";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";
            #endregion
            #region Request
            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = "123456789";
            request.Price = Convert.ToInt32(model.Cart.TotalPrice()).ToString();
            request.PaidPrice = Convert.ToInt32(model.Cart.TotalPrice()).ToString();
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = model.Cart.CartId.ToString();
            request.PaymentChannel = PaymentChannel.MOBILE_WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();
            #region PaymentCard
            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.CardName;
            paymentCard.CardNumber = model.CardNumber;
            paymentCard.ExpireMonth = model.ExpirationMonth;
            paymentCard.ExpireYear = model.ExpirationYear;
            paymentCard.Cvc = model.Cvc;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;
            #endregion
            #region Buyer
            Buyer buyer = new Buyer();
            buyer.Id = "12345";
            buyer.Name = model.FirstName;
            buyer.Surname = model.LastName;
            buyer.GsmNumber = model.PhoneNumber;
            buyer.Email = model.Email;
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress = model.Address;
            buyer.Ip = "85.34.78.112";
            buyer.City = model.City;
            buyer.Country = "Turkey";
            buyer.ZipCode = "34732";
            request.Buyer = buyer;
            #endregion
            #region Addresses
            Address shippingAddress = new Address();
            shippingAddress.ContactName = model.FirstName + " " + model.LastName;
            shippingAddress.City = model.City;
            shippingAddress.Country = "Turkey";
            shippingAddress.Description = model.Address;
            shippingAddress.ZipCode = "34742";
            request.ShippingAddress = shippingAddress;

            Address billingAddress = new Address();
            billingAddress.ContactName = model.FirstName + " " + model.LastName;
            billingAddress.City = model.City;
            billingAddress.Country = "Turkey";
            billingAddress.Description = model.Address;
            billingAddress.ZipCode = "34742";
            request.BillingAddress = billingAddress;
            #endregion
            #region Basket Items
            List<BasketItem> basketItems = new List<BasketItem>();
            BasketItem basketItem;
            foreach (var item in model.Cart.CartItems)
            {
                basketItem = new BasketItem();
                basketItem.Id = item.CartItemId.ToString();
                basketItem.Name = item.BookName;
                basketItem.Category1 = "Kitap";
                basketItem.ItemType = BasketItemType.PHYSICAL.ToString();
                basketItem.Price = Convert.ToInt32(item.Price * item.Quantity).ToString();
                basketItems.Add(basketItem);
            }
            request.BasketItems = basketItems;
            #endregion
            #endregion
            Payment payment = Payment.Create(request, options);
            return payment;
        }
        [NonAction]
        private async Task SaveOrder(OrderViewModel model, string userId)
        {
            Order order = new Order();
            order.UserId = userId;

BooksApp/BooksApp.MVC/ViewComponents/AuthorsViewComponent.cs
using BooksApp.Business.Abstract;
using BooksApp.Entity.Concrete;
using BooksApp.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace BooksApp.MVC.ViewComponents
{
    public class AuthorsViewComponent: ViewComponent
    {
        private readonly IAuthorService _authorManager;

        public AuthorsViewComponent(IAuthorService authorManager)
        {
            _authorManager = authorManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Author> authorList = await _authorManager.GetAllAsync();
            List<AuthorViewModel> authorViewModelList = authorList.Select(a => new AuthorViewModel
            {
                Name=a.FirstName + " " + a.LastName,
                Url=a.Url
            }).ToList();
            return View(authorViewModelList);
        }
    }
}

BooksApp/BooksApp.MVC/ViewComponents/CategoriesViewComponent.cs
using BooksApp.Business.Abstract;
using BooksApp.Entity.Concrete;
using BooksApp.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace BooksApp.MVC.ViewComponents
{
    public class CategoriesViewComponent : ViewComponent
    {
        private readonly ICategoryService _categoryManager;

        public CategoriesViewComponent(ICategoryService categoryManager)
        {
            _categoryManager = categoryManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            CategoryListViewModel categoryListViewModel = new CategoryListViewModel();
            if (RouteData.Values["categoryurl"] != null)
            {
                categoryListViewModel.SelectedCategoryUrl = RouteData.Values["categoryurl"].ToString();
            }
            else
            {
                categoryListViewModel.SelectedCategoryUrl = "";
            }

            List<Category> categories = await _categoryManager.GetAllAsync();
            List<CategoryViewModel> categoryViewModelList = categories
                .Select(c => new CategoryViewModel
                {
                    Name = c.Name,
                    Url = c.Url
                }).ToList();

            categoryListViewModel.CategoryViewModelList= categoryViewModelList;
            
            return View(categoryListViewModel);
        }
    }
}

BooksApp/BooksApp.MVC/ViewComponents/PublishersViewComponent.cs
using BooksApp.Business.Abstract;
using BooksApp.Entity.Concrete;
using BooksApp.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace BooksApp.MVC.ViewComponents
{
    public class PublishersViewComponent:ViewComponent
    {
        private readonly IPublisherService _publisherManager;

        public PublishersViewComponent(IPublisherService publisherManager)
        {
            _publisherManager = publisherManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Publisher> publisherList = await _publisherManager.GetAllAsync();
            List<PublisherViewModel> publisherViewModelList = publisherList.Select(p => new PublisherViewModel
            {
                Name=p.Name,
                Url=p.Url
            }).ToList();
            return View(publisherViewModelList);
        }
    }
}

BooksApp/BooksApp.MVC/Views/BooksShop/BookDetails.cshtml
@model BookDetailsViewModel
<div class="container pt-4">
    <div class="row">
        <div class="col-3">
            <div class="row">
                    <div class="col-12 pb-3">
                        <img class="w-100" src="/images/books/@Model.ImageUrl" />
                    </div>
            </div>
        </div>
        <div class="col-5 bg-light p-3">
            <h3 class="display-6 fs-4 fw-normal text-danger">@Model.Name</h3>
                <a asp-area=""
                   asp-controller="Home"
                   asp-action="AuthorDetails"
                   asp-route-url="@Model.AuthorUrl"
                   class="display-6 fs-6 fw-normal text-primary">
                    @Model.AuthorName
                </a>
            
            <div class="mt-3">
                @for (int i = 0; i < 5; i++)
                {
                    <i class="fa-regular fa-star text-success fa-xs"></i>
                }
            </div>
            @*Kitap Ayrıntıları*@
            <div class="mt-3">
                <h3 class="display-6 fs-4 fw-normal text-danger mt-2">Kitap Ayrıntıları</h3>
                <h6 class="d-inline">Kategori:</h6>
                @for (int i = 0; i < Model.Categories.Count; i++)
                {
                    <span class="fs-6 text-warning">@Model.Categories[i].Name @(i == Model.Categories.Count - 1 ? "" : ",")</span>
                }
                <div class="row mt-3">
                    <div class="col-6">
                        <div>
                            <h6 class="d-inline">Basım Yılı:</h6>
                            <span class="fs-6">@Model.EditionYear</span>
                        </div>
                        <div>
                            <h6 class="d-inline">Baskı Numarası:</h6>
                            <span class="fs-6">@Model.EditionNumber</span>
                        </div>
                    </div>
                    <div class="col-6">
                        <div>
                            <h6 class="d-inline">Sayfa Sayısı:</h6>
                            <span class="fs-6">@Model.PageCount</span>
                        </div>
                        <div>
                            <h6 class="d-inline">Stok Miktarı:</h6>
                            <span class="fs-6">@Model.Stock</span>
                        </div>
                    </div>
                </div>
            </div>
            @*Kitap Özeti*@
            <h3 class="display-6 fs-4 fw-normal text-danger mt-3">Kitap Özeti</h3>
            <p class="fs-6">@Html.Raw(Model.Description)</p>
        </div>
        <div class="col-4">
            @*Fiyat Bölümü*@
            <div class="border-1 border-warning border p-3 pb-0">
                <div class="row">
                    <div class="col-5 d-flex justify-content-center align-items-center">
                        <h5 class="fs-3 text-primary">@($"{Model.Price:C2}")</h5>
                    </div>
                    <div class="col-7">
                        <p class="fs-6 text-center">Tedarik süresi 3-5 gündür.</p>
                        <form asp-area=""
                              asp-controller="Cart"
                              asp-action="AddToCart"
                              method="post">
                            <input type="hidden" asp-for="Id" />
                            <button type="submit" class="btn btn-warning">Sepete Ekle</button>
                            <input class="form-control d-inline" style="width:60px;" type="number" name="quantity" min="1" max="9" value="1" />
                        </form>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 text-center">
                        <p class="text-success mb-2 mt-2 fw-bold">300 TL üzeri kargo bedava!</p>
                    </div>
                </div>
            </div>
            @*Yazar Bilgileri*@
            <div>
                <h3 class="bg-warning p-2 fs-6 text-white fw-bold display-6 mt-3">@Model.AuthorName</h3>
                <img class="float-end me-1" src="https://picsum.photos/100/100" />
                <p class="fs-6">@Html.Raw(Model.AuthorAbout)</p>

            </div>
        </div>
    </div>
</div>

BooksApp/BooksApp.MVC/Views/BooksShop/BookList.cshtml
@model List<BookViewModel>
@{
    ViewData["Title"] = "BooksApp Ana Sayfa";
}
<div class="row">

    <div class="col-10">
        <div class="row g-3">
            @foreach (var bookViewModel in Model)
            {
                <div class="col-2">
                    @await Html.PartialAsync("_BookPartial",bookViewModel)
                </div>
            }
        </div>
    </div>
    <div class="col-2">
        @await Component.InvokeAsync("Categories")
        @await Component.InvokeAsync("Authors")
        @await Component.InvokeAsync("Publishers")
    </div>
</div>