BooksApp/BooksApp.MVC/Areas/Admin/Models/PublisherViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BooksApp.MVC.Areas.Admin.Models
{
    public class PublisherViewModel
    {
        public int Id { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Url { get; set; }
        public List<SelectListItem> Cities { get; set; }
    }
}

BooksApp/BooksApp.MVC/Models/PublisherViewModel.cs
namespace BooksApp.MVC.Models
{
    public class PublisherViewModel
    {
        public string Name { get; set; }
        public string Url { get; set; }
    }
}

BooksApp/BooksApp.MVC/Areas/Admin/Controllers/PublisherController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using BooksApp.Business.Abstract;
using BooksApp.Core;
using BooksApp.Core.Models;
using BooksApp.Entity.Concrete;
using BooksApp.MVC.Areas.Admin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BooksApp.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin")]
    public class PublisherController : Controller
    {
        #region DI
        private readonly IPublisherService _publisherManager;
        private readonly IBookService _bookManager;
        private readonly INotyfService _notyf;

        public PublisherController(IPublisherService publisherManager, INotyfService notyf, IBookService bookManager)
        {
            _publisherManager = publisherManager;
            _notyf = notyf;
            _bookManager = bookManager;
        }
        #endregion
        #region Listeleme
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<Publisher> publisherList = await _publisherManager.GetAllPublishersAsync(false);
            List<PublisherViewModel> publisherViewModelList = publisherList
                .Select(p => new PublisherViewModel
                {
                    Id = p.Id,
                    Name = p.Name,
                    CreatedDate = p.CreatedDate,
                    ModifiedDate = p.ModifiedDate,
                    IsActive = p.IsActive,
                    City = p.City,
                    Country = p.Country,
                    Phone = p.Phone,
                    Url = p.Url
                }).ToList();
            PublisherListViewModel model = new PublisherListViewModel
            {
                PublisherViewModelList = publisherViewModelList,
                SourceAction = "Index"
            };
            return View(model);
        }
        #endregion
        #region Yeni Yayınevi
        [HttpGet]
        public IActionResult Create()
        {
            List<SelectListItem> cities = Jobs.GetCities().Select(x => new SelectListItem
            {
                Text = x.Il,
                Value = x.Il
            }).ToList();
            PublisherAddViewModel publisherAddViewModel = new PublisherAddViewModel
            {
                Cities = cities
            };
            return View(publisherAddViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(PublisherAddViewModel publisherAddViewModel)
        {
            if (ModelState.IsValid)
            {

                Publisher publisher = new Publisher
                {
                    Name = publisherAddViewModel.Name,
                    IsActive = publisherAddViewModel.IsActive,
                    City = publisherAddViewModel.City,
                    Country = publisherAddViewModel.Country,
                    Url = Jobs.GetUrl(publisherAddViewModel.Name),
                    Phone = publisherAddViewModel.Phone

                };
                await _publisherManager.CreateAsync(publisher);
                _notyf.Success("İşlem başarıyla tamamlanmıştır");
                return RedirectToAction("Index");
            }
            List<SelectListItem> cities = Jobs.GetCities().Select(x => new SelectListItem
            {
                Text = x.Il,
                Value = x.Il
            }).ToList();
            publisherAddViewModel.Cities = cities;
            return View(publisherAddViewModel);
        }

        #endregion
        #region Yayınevi Güncelleme
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Publisher publisher = await _publisherManager.GetByIdAsync(id);
            if (publisher == null)
            {
                return NotFound();
            }
            List<SelectListItem> cities = Jobs.GetCities().Select(x => new SelectListItem
            {
                Text = x.Il,
                Value = x.Il
            }).ToList();
            PublisherEditViewModel publisherEditViewModel = new PublisherEditViewModel
            {
                Id = publisher.Id,
                Name = publisher.Name,
                Phone = publisher.Phone,
                City = publisher.City,
                Country = publisher.Country,
                IsActive = publisher.IsActive,
                IsDeleted = publisher.IsDeleted,
                Cities = cities
            };
            return View(publisherEditViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(PublisherEditViewModel publisherEditViewModel)
        {

            if (ModelState.IsValid)
            {
                Publisher publisher = await _publisherManager.GetByIdAsync(publisherEditViewModel.Id);
                publisher.Name = publisherEditViewModel.Name;
                publisher.Phone = publisherEditViewModel.Phone;
                publisher.City = publisherEditViewModel.City;
                publisher.IsActive = publisherEditViewModel.IsActive;
                publisher.IsDeleted = publisherEditViewModel.IsDeleted;
                publisherEditViewModel.Url = Jobs.GetUrl(publisherEditViewModel.Name);
                publisher.Url = publisherEditViewModel.Url;
                publisher.ModifiedDate = DateTime.Now;

                _publisherManager.Update(publisher);
                _notyf.Success("Güncelleme başarıyla tamamlanmıştır.", 5);
                return RedirectToAction("Index");
            }
            List<SelectListItem> cities = Jobs.GetCities().Select(x => new SelectListItem
            {
                Text = x.Il,
                Value = x.Il
            }).ToList();
            publisherEditViewModel.Cities = cities;
            return View(publisherEditViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateIsActive(int id)
        {
            Publisher publisher = await _publisherManager.GetByIdAsync(id);
            if (publisher == null)
            {
                return NotFound();
            }
            publisher.IsActive = !publisher.IsActive;
            publisher.ModifiedDate = DateTime.Now;
            _publisherManager.Update(publisher);
            return RedirectToAction("Index");
        }
        #endregion
        #region Yayınevi Kalıcı Silme
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Publisher publisher = await _publisherManager.GetByIdAsync(id);
            if (publisher == null) return NotFound();
            PublisherDeleteViewModel publisherDeleteViewModel = new PublisherDeleteViewModel
            {
                Id = publisher.Id,
                Name = publisher.Name,
                Url = publisher.Url,
                IsActive = publisher.IsActive,
                IsDeleted = publisher.IsDeleted,
                Phone = publisher.Phone,
                City = publisher.City,
                Country = publisher.Country,
                CreatedDate = publisher.CreatedDate,
                ModifiedDate = publisher.ModifiedDate
            };
            return View(publisherDeleteViewModel);
        }
        [HttpGet]
        public async Task<IActionResult> HardDelete(int id)
        {
            Publisher publisher = await _publisherManager.GetByIdAsync(id);
            if (publisher == null) return NotFound();
            _publisherManager.Delete(publisher);
            await _bookManager.UpdatePublisherOfBooks();
            return RedirectToAction("Index");
        }
        #endregion
        #region Yayınevi Soft Silme
        public async Task<IActionResult> SoftDelete(int id)
        {
            Publisher publisher = await _publisherManager.GetByIdAsync(id);
            if (publisher == null)
            {
                return NotFound();
            }
            publisher.IsDeleted = !publisher.IsDeleted;
            publisher.ModifiedDate = DateTime.Now;
            _publisherManager.Update(publisher);
            string message = publisher.IsDeleted ? "Kayıt silinmiştir. Geri almak için ilgili bölüme geçiniz." : "Kayıt geri alınmıştır.";
            _notyf.Success(message);
            return publisher.IsDeleted ? RedirectToAction("Index") : RedirectToAction("DeletedIndex");
        }
        #endregion
        #region Silinmiş Yayınlevleri Listeleme
        [HttpGet]
        public async Task<IActionResult> DeletedIndex()
        {
            List<Publisher> publisherList = await _publisherManager.GetAllPublishersAsync(true);
            List<PublisherViewModel> publisherViewModelList = publisherList
                .Select(p => new PublisherViewModel
                {
                    Id = p.Id,
                    Name = p.Name,
                    CreatedDate = p.CreatedDate,
                    ModifiedDate = p.ModifiedDate,
                    IsActive = p.IsActive,
                    City = p.City,
                    Country = p.Country,
                    Phone = p.Phone,
                    Url = p.Url
                }).ToList();
            PublisherListViewModel model = new PublisherListViewModel
            {
                PublisherViewModelList = publisherViewModelList,
                SourceAction = "DeletedIndex"
            };
            return View("Index",model);
        }
        #endregion

    }
}

BooksApp/BooksApp.MVC/Areas/Admin/Views/Publisher/Create.cshtml
@model PublisherAddViewModel
<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="card shadow-lg border-0 rounded-lg mt-3">
            <div class="card-header">
                <h3 class="font-weight-light mb-2">Yayınevi Ekleme</h3>
            </div>
            <div class="card-body">
                <form asp-area="Admin" asp-controller="Publisher" asp-action="Create" method="post">
                    <div class="row g-3 mb-3">
                        <div class="col-md-4">
                            <div class="form-floating mb-2 mb-md-0">
                                <input asp-for="Name" class="form-control" placeholder="Kategori adını giriniz.." />
                                <label asp-for="Name"></label>
                            </div>
                            <span class="text-danger" asp-validation-for="Name"></span>
                        </div>
                        <div class="col-md-4">
                            <div class="form-floating mb-2 mb-md-0">
                                <input asp-for="Phone" class="form-control" placeholder="Telefon numarasını giriniz.." />
                                <label asp-for="Phone"></label>
                            </div>
                            <span class="text-danger" asp-validation-for="Phone"></span>
                        </div>
                        <div class="col-md-4">
                            <div class="form-floating">
                                <select class="form-select" asp-for="City" asp-items="@Model.Cities"></select>
                                <label asp-for="City"></label>
                            </div>
                            <span class="text-danger" asp-validation-for="City"></span>
                        </div>
                        <div class="col-md-4">
                            <div class="form-floating">
                                <select class="form-select" asp-for="Country">
                                    <option value="Türkiye">Türkiye</option>
                                </select>
                                <label asp-for="City"></label>
                            </div>
                            <span class="text-danger" asp-validation-for="City"></span>
                        </div>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" asp-for="IsActive" type="checkbox">
                        <label class="form-check-label" for="IsActive">
                            Aktif mi?
                        </label>
                    </div>
                    <div class="mt-4 mb-0">
                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary btn-block">Oluştur</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-footer text-center py-3">
                <div class="small">
                    <a asp-area="Admin" asp-controller="Publisher" asp-action="Index">
                        Tüm Yayınevlerini Listele
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

@section Js{
    @await Html.PartialAsync("_ValidationScriptsPartial");
}

BooksApp/BooksApp.MVC/Areas/Admin/Views/Publisher/Delete.cshtml
@model PublisherDeleteViewModel
<h1 class="display-6 text-danger mt-3">Yayınevi Siliniyor...!</h1>
<hr />
<table class="table w-50 table-bordered">
    <tr>
        <th>Id:</th>
        <td>@Model.Id</td>
        <th>Ad:</th>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <th>Telefon:</th>
        <td>@Model.Phone</td>
        <th>Şehir:</th>
        <td>@Model.City</td>
    </tr>
    <tr>
        <th>Aktif mi?:</th>
        <td class="@(Model.IsActive ? "text-success" : "text-danger") fw-bold ">@(Model.IsActive ? "AKTİF" : "PASİF")
        </td>
        <th>Silinmiş mi?:</th>
        <td class="@(!Model.IsDeleted ? "text-success" : "text-danger") fw-bold ">@(Model.IsDeleted ? "SİLİNMİŞ" :
            "SİLİNMEMİŞ")</td>
    </tr>
    <tr>
        <th>Oluşturulma Tarihi:</th>
        <td>@Model.CreatedDate</td>
        <th>Son Değişiklik Tarihi:</th>
        <td>@Model.ModifiedDate</td>
    </tr>
</table>
<a class="btn btn-warning" asp-area="Admin" asp-controller="Publisher" asp-action="Index">Vazgeç</a>

<a class="btn btn-danger" asp-area="Admin" asp-controller="Publisher" asp-action="HardDelete"
    asp-route-id="@Model.Id">Kalıcı Olarak Sil!</a>
<div class="mt-2">
    <label class="text-danger">* @Model.Name adlı yazar, veri tabanından kalıcı olarak
        silinecektir!</label>
</div>

BooksApp/BooksApp.MVC/Areas/Admin/Views/Publisher/Edit.cshtml
@model PublisherEditViewModel
<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="card shadow-lg border-0 rounded-lg mt-3">
            <div class="card-header">
                <div class="row">
                    <div class="col">
                        <h3 class="font-weight-light mb-2">Yayınevi Güncelleme</h3>
                    </div>
                    <div class="col text-end">
                        <span>
                            <a asp-area="Admin" asp-controller="Publisher" asp-action="Index"
                               class="btn btn-link">Vazgeç</a>
                        </span>
                    </div>
                </div>

            </div>
            <div class="card-body">
                <form asp-area="Admin" asp-controller="Publisher" asp-action="Edit" method="post">
                    <input type="hidden" asp-for="Id" />
                    <div class="row g-3 mb-3">
                        <div class="col-md-4">
                            <div class="form-floating mb-2 mb-md-0">
                                <input asp-for="Name" class="form-control"
                                       placeholder="Yayınevi adını giriniz.." />
                                <label asp-for="Name"></label>
                            </div>
                            <span class="text-danger" asp-validation-for="Name"></span>
                        </div>
                        <div class="col-md-4">
                            <div class="form-floating mb-2 mb-md-0">
                                <input asp-for="Phone" class="form-control" placeholder="Yayınevi telefon numarasını giriniz.." />
                                <label asp-for="Phone"></label>
                            </div>
                            <span class="text-danger" asp-validation-for="Phone"></span>
                        </div>
                        <div class="col-md-4">
                            <div class="form-floating">
                                <select class="form-select" asp-for="City" asp-items="@Model.Cities"></select>
                                <label asp-for="City"></label>
                            </div>
                            <span class="text-danger" asp-validation-for="City"></span>
                        </div>
                        <div class="col-md-4">
                            <div class="form-floating">
                                <select class="form-select" asp-for="Country">
                                    <option value="Türkiye">Türkiye</option>
                                </select>
                                <label asp-for="City"></label>
                            </div>
                            <span class="text-danger" asp-validation-for="City"></span>
                        </div>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" asp-for="IsActive" type="checkbox">
                        <label class="form-check-label" asp-for="IsActive"></label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" asp-for="IsDeleted" type="checkbox">
                        <label class="form-check-label" asp-for="IsDeleted"></label>
                    </div>
                    <div class="mt-4 mb-0">
                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary btn-block">Değişiklikleri Kaydet</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-footer text-center py-3">
                <div class="small">
                    <a asp-area="Admin" asp-controller="Publisher" asp-action="Index">
                        Tüm Yazarları Listele
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

@section Js{
    @await Html.PartialAsync("_ValidationScriptsPartial");
}

BooksApp/BooksApp.MVC/Areas/Admin/Views/Publisher/Index.cshtml
@model PublisherListViewModel
<div class="row my-2">
    <div class="col-md-6">
        <h1 class="display-6">
            @(Model.SourceAction=="Index" ? "Yayınevleri" : "Silinmiş Yayınevleri")
        </h1>
    </div>
    @if (Model.SourceAction=="Index")
    {
        <div class="col-md-6 d-flex align-items-center justify-content-end">
            <a asp-area="Admin"
           asp-controller="Publisher"
           asp-action="Create"
               class="btn btn-primary">Yeni Yayınevi</a>
        </div>
    }
</div>

@if (Model.PublisherViewModelList.Count>0)
{
    <div class="card mb-4">
        <div class="card-body">
            <table id="data-table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Ad</th>
                        <th>Oluşturulma Tarihi</th>
                        <th>Son Değiştirilme Tarihi</th>
                        <th>Şehir</th>
                        <th>Ülke</th>
                        <th>İletişim</th>
                        <th>Aktif mi?</th>
                        <th>İşlemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var publisher in Model.PublisherViewModelList)
                    {
                        <tr>
                            <td>@publisher.Id</td>
                            <td>@publisher.Name</td>
                            <td>@publisher.CreatedDate.ToShortDateString()</td>
                            <td>@publisher.ModifiedDate.ToShortDateString()</td>
                            <td>@publisher.City</td>
                            <td>@publisher.Country</td>
                            <td>@publisher.Phone</td>
                            <td>
                                @if (Model.SourceAction=="Index")
                                {
                                    <form class="form-check"
                              asp-area="Admin"
                              asp-controller="Publisher"
                              asp-action="UpdateIsActive"
                              asp-route-id="@publisher.Id"
                                          id="form-publisher-is-active-@publisher.Id">
                                        <div class="form-check form-switch">
                                            <input class="form-check-input"
                                                   type="checkbox"
                                                   role="switch"
                                                   id="flexSwitchCheckChecked" @(publisher.IsActive ? "checked" : "")
                                                   onchange="document.getElementById(`form-publisher-is-active-@publisher.Id`).submit();">
                                        </div>

                                    </form>
                                }
                                else
                                {
                                    <div class="form-check form-switch">
                                        <input class="form-check-input"
                                               type="checkbox"
                                               role="switch"
                                               id="flexSwitchCheckChecked" @(publisher.IsActive ? "checked" : "" ) disabled>
                                    </div>

                                
                                }
                            </td>
                            <td>
                                <!-- KALICI OLARAK SİLME BUTONU -->
                                <a class="btn btn-danger btn-sm"
                           asp-area="Admin"
                           asp-controller="Publisher"
                           asp-action="Delete"
                           asp-route-id="@publisher.Id">
                                    <i class="fa-solid fa-trash"></i>
                                </a>
@if (Model.SourceAction=="Index")
                                {
                                    
                                
                                <!-- SOFT SİLME BUTONU -->
                        @await Html.PartialAsync("_PublisherDeletePartial",publisher)

                                <!-- GÜNCELLEME BUTONU -->
                                <a class="btn btn-info btn-sm"
                           asp-area="Admin"
                           asp-controller="Publisher"
                           asp-action="Edit"
                           asp-route-id="@publisher.Id">
                                    <i class="fa-solid fa-pen-to-square"></i>
                                    </a>
                                }
                                else
                                {
                                    <a class="btn btn-success btn-sm"
                                       asp-area="Admin"
                                       asp-controller="Publisher"
                                       asp-action="SoftDelete"
                                       asp-route-id="@publisher.Id">
                                        <i class="fa-solid fa-arrow-rotate-left"></i>
                                    </a>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}
else
{
    <div class="alert alert-warning" role="alert">
        Herhangi bir yayınevi bilgisi yoktur.
    </div>
}

@section Css{
    @await Html.PartialAsync("_DataTablesStylesPartial")
}

@section Js{
    @await Html.PartialAsync("_DataTablesScriptsPartial")
}